# Generated by Django 4.2.11 on 2026-04-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_purchase_unique_user_event_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='backup_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='validated_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['backup_code'], name='events_purc_backup__0ca8f1_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['user_id'], name='events_purc_user_id_9a4b24_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['status'], name='events_purc_status_e26e8b_idx'),
        ),
    ]
