# Generated by Django 4.2.11 on 2026-04-24 22:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueueConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(db_index=True, unique=True)),
                ('max_concurrent_users', models.PositiveIntegerField(default=100, help_text='Usuarios simultáneos permitidos antes de activar la cola de espera.')),
                ('payment_timeout_minutes', models.PositiveIntegerField(default=15, help_text='Minutos para completar el pago antes de liberar los asientos reservados.')),
                ('is_queue_active', models.BooleanField(default=False, help_text='True si la cola está actualmente activa para este evento.')),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID del Promotor que realizó la última configuración.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Cola',
                'verbose_name_plural': 'Configuraciones de Cola',
                'db_table': 'queue_config',
            },
        ),
        migrations.CreateModel(
            name='QueueLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('seat_released', 'Asiento liberado por timeout'), ('user_admitted', 'Usuario admitido desde cola'), ('reservation_expired', 'Reserva expirada'), ('queue_activated', 'Cola activada'), ('queue_deactivated', 'Cola desactivada')], max_length=50)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('event_id', models.UUIDField(blank=True, null=True)),
                ('seat_id', models.UUIDField(blank=True, null=True)),
                ('queue_entry_id', models.UUIDField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de Cola',
                'verbose_name_plural': 'Logs de Cola',
                'db_table': 'queue_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('event_id', models.UUIDField(db_index=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, help_text='Cuándo fue notificado de que es su turno.', null=True)),
                ('accessed_at', models.DateTimeField(blank=True, help_text='Cuándo accedió efectivamente a la selección de asientos.', null=True)),
                ('status', models.CharField(choices=[('waiting', 'En espera'), ('admitted', 'Admitido'), ('expired', 'Expirado'), ('left', 'Abandonó')], default='waiting', max_length=20)),
            ],
            options={
                'verbose_name': 'Entrada en Cola',
                'verbose_name_plural': 'Entradas en Cola',
                'db_table': 'queue_entry',
                'unique_together': {('user_id', 'event_id')},
            },
        ),
    ]
