# Generated by Django 4.2.11 on 2026-04-24 22:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seat_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('purchase_id', models.UUIDField(blank=True, help_text='Se llena cuando el pago se completa. NULL si la reserva expiró.', null=True)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Calculado como reserved_at + payment_timeout_minutes de QueueConfig.')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('confirmed', 'Confirmada (pago completado)'), ('expired', 'Expirada (timeout)')], default='active', max_length=20)),
                ('released_at', models.DateTimeField(blank=True, help_text='Se llena cuando la reserva expira y el asiento es liberado (job US20).', null=True)),
            ],
            options={
                'verbose_name': 'Reserva de Asiento',
                'verbose_name_plural': 'Reservas de Asientos',
                'db_table': 'seat_reservation',
                'indexes': [models.Index(fields=['seat_id', 'status'], name='seat_reserv_seat_id_58c97b_idx')],
            },
        ),
    ]
