# Generated by Django 4.2.11 on 2026-03-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('user_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('employee_code', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Admin Profile',
                'verbose_name_plural': 'Admin Profiles',
            },
        ),
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('user_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Buyer Profile',
                'verbose_name_plural': 'Buyer Profiles',
            },
        ),
        migrations.CreateModel(
            name='PromotorProfile',
            fields=[
                ('user_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('comercial_nit', models.CharField(max_length=50, unique=True)),
                ('bank_account', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Promotor Profile',
                'verbose_name_plural': 'Promotor Profiles',
            },
        ),
    ]
