# Generated by Django 4.2.11 on 2026-04-06 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_purchase_status_purchase_unique_user_event_purchase'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchase',
            name='unique_user_event_purchase',
        ),
    ]
