# Generated by Django 4.2.11 on 2026-04-06 14:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_purchase_backup_code_purchase_email_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='waitlist_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='waitlist_threshold',
            field=models.IntegerField(default=90),
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('position', models.IntegerField()),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('notified', 'Notified'), ('converted', 'Converted')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('event', 'user_id')},
            },
        ),
    ]
