# Generated by Django 4.2.11 on 2026-04-08 11:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_cancellation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Order',
                'verbose_name_plural': 'Payment Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('backup_code', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True)),
                ('status', models.CharField(choices=[('valid', 'Válida'), ('used', 'Usada'), ('cancelled', 'Cancelada')], default='valid', max_length=20)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('validated_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.paymentorder')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.tickettype')),
            ],
            options={
                'verbose_name': 'Ticket Instance',
                'verbose_name_plural': 'Ticket Instances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['user_id'], name='events_paym_user_id_62d4f1_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['status'], name='events_paym_status_7625f7_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketinstance',
            index=models.Index(fields=['backup_code'], name='events_tick_backup__629533_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketinstance',
            index=models.Index(fields=['status'], name='events_tick_status_a07d49_idx'),
        ),
    ]
