# Generated by Django 4.2.11 on 2026-04-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_paymentorder_ticketinstance_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'pending'])), fields=('user_id', 'event'), name='unique_active_purchase_per_user_event'),
        ),
    ]
