# Generated by Django 4.2.11 on 2026-04-19 19:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_purchase_unique_active_purchase_per_user_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seat_code', models.CharField(max_length=20)),
                ('row_label', models.CharField(max_length=5)),
                ('seat_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], db_index=True, default='available', max_length=20)),
                ('reserved_at', models.DateTimeField(blank=True, null=True)),
                ('reserved_by', models.UUIDField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='events.tickettype')),
            ],
            options={
                'verbose_name': 'Seat',
                'verbose_name_plural': 'Seats',
                'ordering': ['row_label', 'seat_number'],
                'indexes': [models.Index(fields=['ticket_type', 'status'], name='events_seat_ticket__513432_idx')],
                'unique_together': {('ticket_type', 'seat_code')},
            },
        ),
    ]
