# Generated by Django 4.2.11 on 2026-04-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_add_seat_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='payment_timeout_minutes',
            field=models.IntegerField(default=15),
        ),
    ]
