# Generated by Django 4.2.11 on 2026-04-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_seat_purchase_alter_purchase_status_seatauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='queue_timeout',
            field=models.IntegerField(default=10),
        ),
    ]
