# Generated by Django 4.2.11 on 2026-04-28 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_event_payment_timeout_minutes'),
        ('events', '0016_event_queue_timeout'),
    ]

    operations = [
    ]
