# Generated by Django 4.2.11 on 2026-05-16 01:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_merge_migration_payment_timeout'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('weight', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='events.category')),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
                'indexes': [models.Index(fields=['user_id'], name='events_user_user_id_cb4f67_idx')],
                'unique_together': {('user_id', 'category')},
            },
        ),
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('action_type', models.CharField(choices=[('view', 'Ver evento'), ('favorite', 'Marcar favorito'), ('purchase', 'Comprar')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to='events.event')),
            ],
            options={
                'verbose_name': 'User Behavior',
                'verbose_name_plural': 'User Behaviors',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'action_type'], name='events_user_user_id_5a5bde_idx'), models.Index(fields=['user_id', 'event'], name='events_user_user_id_c3dec1_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('enabled', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='events.category')),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'indexes': [models.Index(fields=['user_id'], name='events_noti_user_id_76fb27_idx')],
                'unique_together': {('user_id', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='events.event')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'read'], name='events_noti_user_id_6907dc_idx'), models.Index(fields=['user_id'], name='events_noti_user_id_a9380d_idx')],
            },
        ),
    ]
