# Generated by Django 4.2.11 on 2026-05-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_add_userbehavior_userpreference_notification_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='admin_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='admin_status',
            field=models.CharField(choices=[('none', 'Sin intervención'), ('modified', 'Modificado por admin'), ('deactivated', 'Dado de baja por admin')], db_index=True, default='none', max_length=20),
        ),
    ]
