# Generated by Django 4.2.11 on 2026-05-18 01:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_event_admin_reason_event_admin_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=200)),
                ('admin_id', models.UUIDField(db_index=True)),
                ('admin_email', models.EmailField(max_length=254)),
                ('action', models.CharField(choices=[('edit', 'Edición de campos'), ('deactivate', 'Dar de baja'), ('reactivate', 'Reactivar evento')], db_index=True, max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('changed_fields', models.JSONField(blank=True, null=True)),
                ('old_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='events.event')),
            ],
            options={
                'verbose_name': 'Event Audit Log',
                'verbose_name_plural': 'Event Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event'], name='eaudit_event_idx'), models.Index(fields=['admin_id'], name='eaudit_admin_idx'), models.Index(fields=['action'], name='eaudit_action_idx'), models.Index(fields=['created_at'], name='eaudit_created_idx'), models.Index(fields=['event', 'created_at'], name='eaudit_event_date_idx')],
            },
        ),
    ]
