# Generated by Django 4.2.11 on 2026-05-19 23:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_rename_events_notification_user_id_idx_events_noti_user_id_a9380d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evento_id', models.UUIDField(db_index=True)),
                ('evento_nombre', models.CharField(max_length=255)),
                ('accion', models.CharField(choices=[('modificacion', 'Modificación de evento'), ('baja', 'Baja de evento'), ('reactivacion', 'Reactivación de evento')], max_length=20)),
                ('motivo', models.TextField()),
                ('campos_modificados', models.JSONField(blank=True, help_text='Dict con los campos que cambiaron: {campo: {antes, despues}}', null=True)),
                ('ejecutado_por_email', models.EmailField(max_length=254)),
                ('ejecutado_por_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admin Audit Log',
                'verbose_name_plural': 'Admin Audit Logs',
                'db_table': 'admin_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='userfavorite',
            name='events_user_user_id_8b627f_idx',
        ),
        migrations.AddField(
            model_name='event',
            name='admin_baja_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el administrador dio de baja el evento.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='admin_baja_motivo',
            field=models.TextField(blank=True, help_text='Motivo de baja registrado por el administrador.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='admin_baja_por',
            field=models.EmailField(blank=True, help_text='Email del administrador que ejecutó la baja.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='admin_status',
            field=models.CharField(choices=[('visible', 'Visible'), ('dado_de_baja', 'Dado de baja')], db_index=True, default='visible', max_length=20),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['evento_id'], name='admin_audit_evento__9ce38f_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['ejecutado_por_id'], name='admin_audit_ejecuta_bd8611_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['accion'], name='admin_audit_accion_464c5d_idx'),
        ),
    ]
