# Generated by Django 4.2.11 on 2026-05-18 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_notification_update_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='events_noti_user_id_a9380d_idx',
            old_name='events_notification_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='events_noti_user_id_2dcfa8_idx',
            old_name='events_notification_user_leida_idx',
        ),
    ]
