# Generated by Django 4.2.11 on 2026-05-20 02:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_adminauditlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evento_id', models.UUIDField(db_index=True)),
                ('evento_nombre', models.CharField(max_length=255)),
                ('operacion', models.CharField(choices=[('create', 'Creación'), ('update', 'Actualización'), ('delete', 'Eliminación'), ('soft_delete', 'Baja lógica')], max_length=20)),
                ('estado_anterior', models.JSONField(blank=True, help_text='Estado del evento ANTES del cambio. Null en creaciones.', null=True)),
                ('estado_nuevo', models.JSONField(blank=True, help_text='Estado del evento DESPUÉS del cambio. Null en eliminaciones.', null=True)),
                ('campos_modificados', models.JSONField(blank=True, help_text='Dict {campo: {antes, despues}} de campos que cambiaron.', null=True)),
                ('motivo_baja', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Event Audit Log',
                'verbose_name_plural': 'Event Audit Logs',
                'db_table': 'event_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['evento_id'], name='event_audit_evento__f9d04c_idx'), models.Index(fields=['operacion'], name='event_audit_operaci_d11a9f_idx'), models.Index(fields=['evento_id', 'operacion'], name='event_audit_evento__6347e0_idx'), models.Index(fields=['created_at'], name='event_audit_created_c15585_idx')],
            },
        ),
    ]
