# Generated by Django 4.2.11 on 2026-06-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_promotionplan_eventpromotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpromotion',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, help_text='Monto en BOB pagado por esta promoción (snapshot del precio del plan).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='eventpromotion',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Fecha de inicio de la promoción (cuando se confirma el pago).', null=True),
        ),
    ]
