# Generated by Django 4.2.11 on 2026-03-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_data_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_role', models.CharField(blank=True, max_length=50, null=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de Eliminación',
                'verbose_name_plural': 'Registros de Eliminaciones',
                'db_table': 'account_deletion_logs',
            },
        ),
    ]
