# Generated by Django 4.2.11 on 2026-03-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_accountdeletionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
