# Generated by Django 4.2.11 on 2026-05-18 01:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_profile_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('active', 'Activo'), ('suspended', 'Suspendido'), ('banned', 'Bloqueado permanentemente')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='suspended_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admin_id', models.UUIDField(db_index=True)),
                ('admin_email', models.EmailField(max_length=254)),
                ('target_user_id', models.UUIDField(db_index=True)),
                ('target_user_email', models.EmailField(max_length=254)),
                ('action', models.CharField(choices=[('suspend', 'Suspender cuenta'), ('ban', 'Bloquear permanentemente'), ('reactivate', 'Reactivar cuenta'), ('delete', 'Eliminar cuenta'), ('role_change', 'Cambiar rol'), ('create_admin', 'Crear administrador'), ('update_admin', 'Actualizar permisos administrador')], db_index=True, max_length=30)),
                ('reason', models.TextField(blank=True, null=True)),
                ('previous_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admin Audit Log',
                'verbose_name_plural': 'Admin Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin_id'], name='users_admin_admin_i_c282ce_idx'), models.Index(fields=['target_user_id'], name='users_admin_target__a18fd9_idx'), models.Index(fields=['action'], name='users_admin_action_27b4ff_idx'), models.Index(fields=['created_at'], name='users_admin_created_20d789_idx')],
            },
        ),
    ]
