# Generated by Django 4.2.11 on 2026-05-18 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_account_status_user_suspended_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminauditlog',
            name='action_category',
            field=models.CharField(choices=[('user_mgmt', 'Gestión de usuarios'), ('admin_mgmt', 'Gestión de administradores')], db_index=True, default='user_mgmt', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superadmin',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='adminauditlog',
            name='action',
            field=models.CharField(choices=[('suspend', 'Suspender cuenta'), ('ban', 'Bloquear permanentemente'), ('reactivate', 'Reactivar cuenta'), ('delete', 'Eliminar cuenta'), ('role_change', 'Cambiar rol'), ('create_admin', 'Crear administrador'), ('update_admin', 'Actualizar permisos administrador'), ('grant_superadmin', 'Otorgar SuperAdmin'), ('revoke_superadmin', 'Revocar SuperAdmin')], db_index=True, max_length=30),
        ),
    ]
