# Generated by Django 4.2.11 on 2026-05-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_adminauditlog_action_category_user_is_superadmin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspensionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_role', models.CharField(blank=True, max_length=50, null=True)),
                ('motivo', models.TextField()),
                ('suspendido_por_email', models.EmailField(max_length=254)),
                ('suspended_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de Suspensión',
                'verbose_name_plural': 'Registros de Suspensiones',
                'db_table': 'suspension_logs',
                'ordering': ['-suspended_at'],
            },
        ),
    ]
